[toolchain]
channel = "stable"
components = ["rustfmt", "clippy", "rust-analyzer"]
targets = [
  "aarch64-apple-darwin",
  "aarch64-unknown-linux-gnu",
  "aarch64-unknown-linux-musl",
  "i686-unknown-linux-gnu",
  "i686-unknown-linux-musl",
  "x86_64-apple-darwin",
  "x86_64-unknown-linux-gnu",
  "x86_64-unknown-linux-musl",
]
profile = "default"
