[package]
name = "version-manager"
version = "0.1.0-rc.1"
edition = "2021"
description = "A simple version manager for your projects."
license = "GPL-3.0-or-later"
authors = ["Annie Ehler <annie.ehler.4@gmail.com>"]
readme = "./README.md"
repository = "https://github.com/annie444/version"
keywords = ["version", "manager", "cli", "rust"]
categories = ["command-line-utilities", "config", "development-tools", "development-tools::build-utils"]


# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
clap = { version = "4.5.4", features = ["derive", "color"] }
clap_complete = "4.5.1"
clio = { version = "0.3.5", features = ["clap", "clap-parse"] }
regex = "1.10.4"
serde = { version = "1.0.197", features = ["derive"] }
toml = "0.8.12"
